# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-yaml
          - id: check-json
          - id: check-added-large-files
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/pycqa/flake8
      rev: 7.1.0
      hooks:
          - id: flake8
            args: ["--ignore=W503,E402,F401"]
            additional_dependencies: ["flake8-print"]
    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
          - id: black
            args: [--line-length=88]
    - repo: https://github.com/timothycrosley/isort
      rev: 5.13.2
      hooks:
          - id: isort
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.41.0
      hooks:
          - id: markdownlint
            args: [--fix]
